### ISSUE TITLE
Level 17 StackLayout issue

### ISSUE THREAD

**Issue by alexanderolssen** [rdlauer/nslayouts#1]
<img width="745" alt="screenshot 2019-02-20 at 21 46 17" src="https://user-images.githubusercontent.com/25307923/53116149-02fce380-3559-11e9-9d20-ac53cfd0934a.png">

At first i want to say thanks to devs, who made this game! I'm really enjoying learning by playing it.
But not sure it's bug or not (i have not previous development experience) that the parent StackLayout  closing tag missing a "/"

**Comment by rdlauer** [comment]
OMG - I'm embarrassed to say I missed this issue long ago (a bad side effect of turning off email notifications...). I'll get this fixed :)
