### ISSUE TITLE
Order of html attributes shouldn't matter

### ISSUE THREAD

**Issue by julianorinyol** [rdlauer/nslayouts#4]
Hi, 
On level 4

placing the horizontalAlignment attribute before the other attributes will not be successful

failing version:
`<Image  horizontalAlignment="left" src="res://angular" stretch="none"></Image>
<Image  horizontalAlignment="center" src="res://vue" stretch="none"></Image>
<Image horizontalAlignment="right" src="res://preact" stretch="none"></Image>
`

while, the only difference in the correct version is the order of these attributes.
successful version version:
`<Image src="res://angular" stretch="none" horizontalAlignment="left"></Image>
<Image src="res://vue" stretch="none" horizontalAlignment="center"></Image>
<Image src="res://preact" stretch="none" horizontalAlignment="right"></Image>`

As far as i'm aware the attribute order does not matter in NativeScript (correct me if i'm wrong).

Expected result: 
Attribute order should not matter

By the way, thanks for making this tutorial its great,  I always prefer to first learn systems for layout and styling in an interactive way.

**Comment by rdlauer** [comment]
You're right, it shouldn't matter. But the solutions are analyzed via basic string matching. Unless we want to get fancy with some regex I don't see this changing 🤷‍♂
