### ISSUE TITLE
Display screen does not react to valid nativescript options

### ISSUE THREAD

**Issue by julianorinyol** [rdlauer/nslayouts#5]
hi,

The tutorial appears like its an interactive environment where you can type **any** nativescript options and see the results displayed on the display phone screen.

Currently, it only reacts to the correct answer and not to variations.

Its obviously unreasonable to expect it to accept **any** valid nativescript, but I think its reasonable to expect that it accepts all the options for the current attribute or element that it is teaching 

for a specific example: 
on Level 6, we are learning WrapLayout's orientation attribute,

it would be nice if it could accept: 

`<WrapLayout orientation="horizontal">` and display what that would look like on the phone screen

**Comment by rdlauer** [comment]
This is outside the scope of what the tutorial is meant to do. For more flexible usage, we recommend heading to the [NativeScript Playground](https://play.nativescript.org/)
